### ISSUE TITLE
Example animations at axis.davepagurek.com don't display interpolation.

### ISSUE THREAD

**Issue by roke-julian-lockhart** [pahgawk/Axis#3]
The animations at https://axis.davepagurek.com/ don't appear interpolated – they display as mere frames, so as if they're violently twitching.

**Comment by davepagurek** [comment]
Haha I think that's just a user issue, it just displays examples that users have made with no manual curation. If you keep going back you'll see some more that use interpolation more, e.g. https://axis.davepagurek.com/view/261
